In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
student_df=pd.read_csv('student_dropout_dataset_v3.csv')

In [3]:
print(student_df)

      Student_ID   Age  Gender  Family_Income Internet_Access  \
0              1  22.1    Male        25000.0             Yes
1              2  20.7    Male        25000.0             Yes
2              3  22.4    Male        40183.0             Yes
3              4  24.4    Male            NaN             Yes
4              5  20.5  Female        25319.0             Yes
...          ...   ...     ...            ...             ...
9995        9996  23.9  Female        42286.0              No
9996        9997  17.0  Female        61103.0             Yes
9997        9998  19.4    Male        25000.0             Yes
9998        9999  22.1  Female        40302.0             Yes
9999       10000  22.4  Female        76796.0             Yes

      Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  \
0                    3.36             86.1                      2
1                    4.30             68.0                      2
2                    4.40             70.9                      0
3                     NaN             82.2                      2
4                    4.19             75.7                      1
...                   ...              ...                    ...
9995                 4.62             92.0                      0
9996                 2.87             75.2                      3
9997                 4.73             74.9                      4
9998                 5.85             74.2                      1
9999                 4.95             83.7                      1

      Travel_Time_Minutes Part_Time_Job Scholarship  Stress_Index   GPA  \
0                    20.4           Yes          No           5.5  0.96
1                    44.0            No          No           6.8  1.28
2                    48.9           Yes          No           5.5  1.68
3                    38.6            No          No           NaN  1.78
4                    23.0            No          No           7.0  1.48
...                   ...           ...         ...           ...   ...
9995                 10.0           Yes         Yes           5.5  1.60
9996                 32.4            No         Yes           6.7  3.09
9997                 25.4            No          No           3.5  3.45
9998                  5.0            No         Yes           6.2  3.35
9999                 15.5           Yes          No           7.9  2.17

      Semester_GPA  CGPA Semester   Department Parental_Education  Dropout
0             0.90  0.90   Year 1         Arts        High School        0
1             1.20  1.19   Year 3  Engineering           Bachelor        1
2             1.32  1.32   Year 1         Arts             Master        0
3             1.77  1.77   Year 1           CS        High School        1
4             0.91  0.87   Year 4     Business           Bachelor        0
...            ...   ...      ...          ...                ...      ...
9995          0.99  0.97   Year 2         Arts           Bachelor        0
9996          3.09  3.09   Year 1     Business             Master        1
9997          3.37  3.43   Year 4     Business           Bachelor        0
9998          3.34  3.34   Year 1           CS        High School        0
9999          2.20  2.20   Year 1         Arts             Master        0

[10000 rows x 19 columns]

In [4]:
student_df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [5]:
student_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  object
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  object
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  object
 10  Scholarship            10000 non-null  object
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  object
 16  Department             10000 non-null  object
 17  Parental_Education     9489 non-null   object
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), object(7)
memory usage: 1.4+ MB

In [6]:
student_df.describe()

,Student_ID,Age,Family_Income,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Stress_Index,GPA,Semester_GPA,CGPA,Dropout
count,10000.00000,10000.00000,9500.000000,9500.000000,10000.00000,10000.000000,10000.00000,9500.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,21.02606,38377.247474,4.014592,81.73683,1.799700,30.17926,5.507147,2.308440,2.300057,2.298761,0.23540
std,2886.89568,2.13981,20496.232179,1.295450,8.22093,1.344307,11.91887,1.765951,1.061717,1.074407,1.072555,0.42427
min,1.00000,17.00000,25000.000000,0.500000,38.20000,0.000000,5.00000,1.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,19.50000,25000.000000,3.160000,76.40000,1.000000,21.90000,4.300000,1.550000,1.520000,1.520000,0.00000
50%,5000.50000,21.00000,29740.500000,4.000000,81.80000,2.000000,30.20000,5.500000,2.350000,2.350000,2.350000,0.00000
75%,7500.25000,22.50000,44520.000000,4.870000,87.30000,3.000000,38.40000,6.700000,3.120000,3.150000,3.150000,0.00000
max,10000.00000,29.60000,316601.000000,8.980000,100.00000,8.000000,74.90000,10.000000,4.000000,4.000000,4.000000,1.00000

In [7]:
student_df.isnull().sum()

Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

In [8]:
student_df['Family_Income'].fillna(student_df['Family_Income'].mean(),inplace=True)
student_df['Study_Hours_per_Day'].fillna(student_df['Study_Hours_per_Day'].mean(),inplace=True)
student_df['Stress_Index'].fillna(student_df['Stress_Index'].mean(),inplace=True)
student_df['Parental_Education'].fillna(student_df['Parental_Education'].mode()[0], inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20104\1086420169.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_df['Family_Income'].fillna(student_df['Family_Income'].mean(),inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20104\1086420169.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_df['Study_Hours_per_Day'].fillna(student_df['Study_Hours_per_Day'].mean(),inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20104\1086420169.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_df['Stress_Index'].fillna(student_df['Stress_Index'].mean(),inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20104\1086420169.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  student_df['Parental_Education'].fillna(student_df['Parental_Education'].mode()[0], inplace=True)

In [9]:
print(student_df.dtypes)

Student_ID                 int64
Age                      float64
Gender                    object
Family_Income            float64
Internet_Access           object
Study_Hours_per_Day      float64
Attendance_Rate          float64
Assignment_Delay_Days      int64
Travel_Time_Minutes      float64
Part_Time_Job             object
Scholarship               object
Stress_Index             float64
GPA                      float64
Semester_GPA             float64
CGPA                     float64
Semester                  object
Department                object
Parental_Education        object
Dropout                    int64
dtype: object

In [10]:
student_df.drop('Student_ID', axis= 1)

,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,22.1,Male,25000.000000,Yes,3.360000,86.1,2,20.4,Yes,No,5.500000,0.96,0.90,0.90,Year 1,Arts,High School,0
1,20.7,Male,25000.000000,Yes,4.300000,68.0,2,44.0,No,No,6.800000,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,22.4,Male,40183.000000,Yes,4.400000,70.9,0,48.9,Yes,No,5.500000,1.68,1.32,1.32,Year 1,Arts,Master,0
3,24.4,Male,38377.247474,Yes,4.014592,82.2,2,38.6,No,No,5.507147,1.78,1.77,1.77,Year 1,CS,High School,1
4,20.5,Female,25319.000000,Yes,4.190000,75.7,1,23.0,No,No,7.000000,1.48,0.91,0.87,Year 4,Business,Bachelor,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23.9,Female,42286.000000,No,4.620000,92.0,0,10.0,Yes,Yes,5.500000,1.60,0.99,0.97,Year 2,Arts,Bachelor,0
9996,17.0,Female,61103.000000,Yes,2.870000,75.2,3,32.4,No,Yes,6.700000,3.09,3.09,3.09,Year 1,Business,Master,1
9997,19.4,Male,25000.000000,Yes,4.730000,74.9,4,25.4,No,No,3.500000,3.45,3.37,3.43,Year 4,Business,Bachelor,0
9998,22.1,Female,40302.000000,Yes,5.850000,74.2,1,5.0,No,Yes,6.200000,3.35,3.34,3.34,Year 1,CS,High School,0
9999,22.4,Female,76796.000000,Yes,4.950000,83.7,1,15.5,Yes,No,7.900000,2.17,2.20,2.20,Year 1,Arts,Master,0

In [11]:
student_df=pd.get_dummies(student_df,drop_first=True)

In [12]:
x= student_df.drop('Dropout', axis=1)
y= student_df['Dropout']

In [14]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [18]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [19]:
y_pred = model.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:" ,accuracy)

Accuracy: 0.8135

In [21]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[1446   99]
 [ 274  181]]

In [23]:
print(student_df["Dropout"].value_counts())

Dropout
0    7646
1    2354
Name: count, dtype: int64

classification report

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89      1545
           1       0.65      0.40      0.49       455

    accuracy                           0.81      2000
   macro avg       0.74      0.67      0.69      2000
weighted avg       0.80      0.81      0.80      2000